### ISSUE TITLE
MAP MRR

### ISSUE THREAD

**Issue by xuezzz** [hitvoice/RE2#7]
Wikiqa数据集，计算ＭＡＰ时出错了：
Traceback (most recent call last):tes 10 loss: 0.2441 lr: 0.0010 gnorm: 0.1420
  File "train.py", line 48, in <module>
    main()
  File "train.py", line 31, in main
    states = trainer.train()
  File "/media/xuezzz/xueee/simple-effective-text-matching-master/src/trainer.py", line 66, in train
    score, dev_stats = model.evaluate(sess, dev_batches)
  File "/media/xuezzz/xueee/simple-effective-text-matching-master/src/model.py", line 187, in evaluate
    stats.update(metrics[metric](outputs))
  File "/media/xuezzz/xueee/simple-effective-text-matching-master/src/utils/metrics.py", line 80, in ranking
    map_, mrr = [float(s[-6:]) for s in stdout.strip().split('\n')]
  File "/media/xuezzz/xueee/simple-effective-text-matching-master/src/utils/metrics.py", line 80, in <listcomp>
    map_, mrr = [float(s[-6:]) for s in stdout.strip().split('\n')]
ValueError: could not convert string to float:
你知道是哪的问题嘛？谢谢！

**Comment by xuezzz** [comment]
Readme看漏了，已解决。
